move_to_spot:
  ros__parameters:
    corner1:
      x: 0.77
      y: 0.08
      z: 0.0
      yaw: 0.18
    corner2:
      x: -0.58
      y: -1.29
      z: 0.0
      yaw: 0.99
    pedestrian:
      x: 0.17
      y: 0.12
      z: 0.0
      yaw: 0.0
    
    
    